### PR TITLE
Issue-95: An Author Name other than Alley Breaks PHP Namespaces

### LINKED ISSUE #95: An Author Name other than Alley Breaks PHP Namespaces
### Description of the bug

If an author name other than `Alley` is used while scaffolding, `use` statements inside of PHP feature files will break because `Alley` is replaced in the namespace with the author name provided.

### Steps To Reproduce

1. Run `make`
2. Use a different author name such as `github`
3. After scaffolding completes note how the `use` statements inside of PHP feature files has been changed causing things to not work.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by anubisthejackle**
## Summary
This PR addresses the issue described in [#95](https://github.com/alleyinteractive/create-wordpress-project/issues/95) - Fixes #95

### Description of the bug

If an author name other than `Alley` is used while scaffolding, `use` statements inside of PHP feature files will break because `Alley` is replaced in the namespace with the author name provided. This has been fixed by ensuring that the `Alley` username is not replaced during configuration.

### Steps To Reproduce

1. Run `make`
2. Use a different author name such as `github`
3. After scaffolding completes note how the `use` statements inside of PHP feature files has been changed causing things to not work.

### Changes Made

- Prevented the wiping out of the `Alley` username during the configuration process.
- Adjusted the mechanism to use the author's username instead of the name to avoid breaking `use` statements in PHP feature files.

### Additional Information

_No response_

### CODE REVIEW

File: configure.php [hunk 1]
```diff
@@ -424,7 +422,7 @@ function install_plugin( array $plugin_data, bool $prompt, &$installed_plugins )
 	'CREATE_WORDPRESS_PROJECT'     => strtoupper( str_replace( '-', '_', $project_name_slug ) ),
 
 	'vendor_name'                  => $vendor_name,
-	'alleyinteractive'             => $vendor_slug,
```
Comment (srtfisher) [inline configure.php:427]: Removing this would make something like this line https://github.com/alleyinteractive/create-wordpress-project/blob/develop/composer.json#L2 not updated, right?

Comment (anubisthejackle) [reply configure.php:427]: True. If we have more of those hardcoded that we need to keep I think we would want to be a lot more specific about the replacements. Something like replacing the whole thing with `$author_username . '/' . $project_name_slug`

**Review by mboynes — APPROVED** [review]
